class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    #TODO: find_by must be rewritten in order to check all fields, not only the locality
    @address = Address.find_by(locality: params[:building][:addresses][:locality])
    if @address.nil?
      #TODO: fix the following line: ActiveModel::ForbiddenAttributesError
      #I need to know how to create new enty for Address
      @address = Address.new(params[:building][:addresses])
    end
    params[:building][:addresses].delete
    params[:building][:address_id] = @address
    # TODO: from here ahead the code was generated by scaffold
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:name, :route, :street_number, :postal_code, :hamlet, :latitude, :longitude, :locality_id)
    end
end
